/* --- DML ---*/


--> Cad_setor
INSERT ALL
	
	INTO CAD_SETOR (SET_COD, SET_DESCRICAO, SET_ATIVO)
		VALUES ('MP1','Maquina de Pape','S')
	
	INTO CAD_SETOR (SET_COD, SET_DESCRICAO, SET_ATIVO)
		VALUES ('MP2','Maquina de Pape','S')
	
	INTO CAD_SETOR (SET_COD, SET_DESCRICAO, SET_ATIVO)
		VALUES ('MP3','Maquina de Pape','S')
	
	INTO CAD_SETOR (SET_COD, SET_DESCRICAO, SET_ATIVO)
		VALUES ('CLD','Caldeiras','S')
	
	INTO CAD_SETOR (SET_COD, SET_DESCRICAO, SET_ATIVO)
		VALUES ('SPC','Super Calandras','N')
	
	INTO CAD_SETOR (SET_COD, SET_DESCRICAO, SET_ATIVO)
		VALUES ('UTI','Utilidades','S')
	
	INTO CAD_SETOR (SET_COD, SET_DESCRICAO, SET_ATIVO)
		VALUES ('ADM','Administrativo','S')
	
	INTO CAD_SETOR (SET_COD, SET_DESCRICAO, SET_ATIVO)
		VALUES ('MAN','Manutenção','S')
	
	INTO CAD_SETOR (SET_COD, SET_DESCRICAO, SET_ATIVO)
		VALUES ('LUT','Unidade Lutepel','S')
	
	INTO CAD_SETOR (SET_COD, SET_DESCRICAO, SET_ATIVO)
		VALUES ('CON','Conversão','S')
SELECT * FROM DUAL;



--> Cad_Equipamento
INSERT ALL
	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0001', 'Ksb', 'MChem 80-200', 730, 7, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0002', 'Equipe', 'BCM 125-300 AY', 730, 7, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0003', 'Equipe', 'SN 100-21', 730, 7, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0004', 'Equipe', 'BRF - YD - 31', 730, 7, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0005', 'Imbil', 'E 4', 730, 7, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0006', 'Imbil', 'E 4', 730, 7, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0007', 'Equipe', 'BCM 125-300 W', 730, 7, 1100, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0008', 'Equipe', 'BCM 125-300 W', 730, 7, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0009', 'Imbil', 'INI K 80-250', 730, 7, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0010', 'Imbil', 'BEK 40/7', 365, 7, 3550, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0011', 'Imbil', 'BEK 40/7', 365, 7, 3550, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0012', 'Ksb', 'MChem 50-200', 730, 7, 3550, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0013', 'Ksb', 'MChem 50-200', 730, 7, 3550, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0014', 'Ksb', 'MBloco 25-200 R', 730, 7, 3550, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0015', 'Ksb', 'MBloco 25-200 R', 730, 7, 3550, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0016', 'Camberra', '3405L (10X12-17D)', 2190, 14, 1100, 'N')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0017', 'Equipe', 'BCM 90-300 Y', 730, 7, 1100, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0018', 'Equipe', 'BCM 75-300 Y', 730, 7, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BV001', 'Reconditec', '2001', 1460, 14, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BV002', 'Reconditec', '2001', 1460, 14, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BV003', 'Reconditec', '2001', 1460, 14, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BV004', 'Reconditec', '2001', 1460, 14, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BV005', 'Reconditec', '2001', 1460, 14, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BV006', 'Reconditec', '2001', 1460, 14, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0019', 'Camberra', 'XLT3196 (6X8-13)', 730, 7, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0020', 'Equipe', 'BRF - YD - 31', 730, 7, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0021', 'Equipe', 'SN - 100 - 26', 730, 7, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0022', 'Equipe', 'BCM 125-300 BY', 730, 7, 1100, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0023', 'Equipe', 'BCM 125-300 Y', 730, 7, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0024', 'Equipe', 'BCM 125-300 Y', 730, 7, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0025', 'Imbil', 'ITAP 32-160', 730, 7, 3550, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0026', 'Imbil', 'BEW 32/8', 365, 15, 3550, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0027', 'Imbil', 'INI B 50-200', 730, 7, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0028', 'Equipe', 'BCM 125-300 AW', 730, 7, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0029', 'Equipe', 'BCM 90-300 Y', 730, 7, 1770, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0030', 'Equipe', 'BCM 90-300 W', 730, 7, 1100, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0031', 'Equipe', 'BCM 125-300 AY', 730, 7, 1100, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0032', 'Equipe', 'BCM 125-300 AW', 730, 7, 1100, 'S')

	INTO CAD_EQUIPAMENTO (EQU_SUB_TAG, EQU_FABRICANTE, EQU_MODELO, EQU_VIDA_UTIL, EQU_FREQ_LUB, EQU_RPM, EQU_RPM_FIXO)
		VALUES ('BB0033', 'Equipe', 'BCM 125-300 AW', 730, 7, 1100, 'S')
SELECT * FROM DUAL;


--> Cad_Colaborador
INSERT ALL
	INTO CAD_COLABORADOR (COL_ID_SETOR, COL_COD, COL_NOME, COL_FUNCAO, COL_ATIVO)
		VALUES (9, 0, 'ADMIN', 'ADMIN', 'N')

	INTO CAD_COLABORADOR (COL_ID_SETOR, COL_COD, COL_NOME, COL_FUNCAO, COL_ATIVO)
		VALUES (8, 2657, 'João Antonio', 'Tecnico', 'S')

SELECT * FROM DUAL;



--> CAD_POSICAO
INSERT ALL

	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 1, 'BB.WW-2201', 'Bomba da caixa de selagem', DATE DATE '2012-11-05', 'S')

	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 2, 'BB.WI-2601', 'Bomba da canaleta de vacuo', DATE DATE '2012-11-05', 'S')
	
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 1, 1, 'BB.WW-2201', 'Bomba da caixa de selagem', DATE '2012-11-05', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 2, 1, 'BB.WI-2601', 'Bomba da canaleta de vacuo', DATE '2012-11-05', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 3, 1, 'BB.WI-2602', 'Bomba da canaleta geral', DATE '2012-11-05', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 4, 1, 'BB.WW-2601', 'Bomba de agua branca (TQ 2B)', DATE '2012-11-05', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 5, 1, 'BB.RJ-2602', 'Bomba de agua do piso 01', DATE '2012-11-05', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 6, 1, 'BB.RJ-2603', 'Bomba de agua do piso 02', DATE '2012-11-05', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 7, 1, 'BB.WT-2101', 'Bomba de agua fibrosa 01', DATE '2012-11-05', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 8, 1, 'BB.WT-2102', 'Bomba de agua fibrosa 02', DATE '2012-11-05', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 9, 1, 'BB.WI-2205', 'Bomba de alimentação da torre', DATE '2012-11-05', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 10, 1, 'BB.WI-2201', 'Bomba de alta pressão 01', DATE '2012-11-05', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 11, 1, 'BB.WI-2202', 'Bomba de alta pressão 02', DATE '2012-11-05', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 12, 1, 'BB.WI-2203', 'Bomba de baixa pressão 01', DATE '2018-04-10', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 13, 1, 'BB.WI-2204', 'Bomba de baixa pressão 02', DATE '2018-04-10', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 14, 3, 'BB.CD-2301', 'Bomba de condensado 01', DATE '2017-05-07', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 15, 3, 'BB.CD-2302', 'Bomba de condensado 02', DATE '2017-06-06', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 16, 1, 'BB.MA-2113', 'Bomba de mistura (bipartida)', DATE '2012-11-05', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 17, 2, 'BB.WI-2206', 'Bomba de selagem das bvs (torre)', DATE '2012-11-05', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 18, 1, 'BB.MA-2109', 'Bomba do tanque transbordo (cx nivel)', DATE '2018-06-12', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 19, 1, 'BB.AN-2201', 'Bomba de vacuo 1', DATE '2017-10-09', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 20, 1, 'BB.AN-2202', 'Bomba de vacuo 2', DATE '2016-10-17', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 21, 1, 'BB.AN-2203', 'Bomba de vacuo 3', DATE '2014-09-01', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 22, 1, 'BB.AN-2204', 'Bomba de vacuo 4', DATE '2016-08-17', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 23, 1, 'BB.AN-2205', 'Bomba de vacuo 5', DATE '2018-03-07', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 24, 1, 'BB.AN-2206', 'Bomba de vacuo 6', DATE '2018-07-17', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 25, 1, 'BB.MA-2110', 'Bomba do 1º estagio', DATE '2012-11-05', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 26, 1, 'BB.MA-2111', 'Bomba do 2º estagio', DATE '2018-07-17', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 27, 1, 'BB.MA-2112', 'Bomba do 3º estagio', DATE '2018-07-17', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 28, 1, 'BB.RJ-2601', 'Bomba do couch pit', DATE '2012-11-05', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 29, 4, 'BB.MA-2101', 'Bomba do hidrapulper 01', DATE '2012-11-05', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 30, 4, 'BB.MA-2102', 'Bomba do hidrapulper 02', DATE '2018-08-09', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 31, 1, 'BB.WP-2201', 'Bomba do pichaço 01', DATE '2017-09-12', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 32, 1, 'BB.WP-2202', 'Bomba do pichaço 02', DATE '2017-04-07', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 33, 1, 'BB.PQ-2501', 'Bomba do tanque de amido', DATE '2015-11-05', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 34, 1, 'BB.MA-2103', 'Bomba do tanque de massa 01', DATE '2012-11-05', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 35, 1, 'BB.MA-2104', 'Bomba do tanque de massa 02', DATE '2018-01-06', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 36, 1, 'BB.MA-2105', 'Bomba do tanque de massa 03', DATE '2012-11-05', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 37, 1, 'BB.MA-2106', 'Bomba do tanque de massa 4A', DATE '2012-11-05', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 38, 1, 'BB.MA-2107', 'Bomba do tanque de massa 4B1', DATE '2017-10-15', 'S')
		
	INTO CAD_POSICAO (POS_ID_SETOR, POS_ID_EQUIP, POS_TAG, POS_DESCRICAO, POS_DT_INSTALACAO, POS_ATIVO)
		VALUES (2, 39, 1, 'BB.MA-2108', 'Bomba do tanque de massa 4B2', DATE '2012-11-05', 'S');
		
SELECT * FROM DUAL;



--> CAD_TP_ALERTA
INSERT ALL

	INTO CAD_TP_ALERTA (TPA_DESCRICAO, TPA_GRAU, TPA_ATIVO)
		VALUES ('Normal',0,'S');

	INTO CAD_TP_ALERTA (TPA_DESCRICAO, TPA_GRAU, TPA_ATIVO)
		VALUES ('Aceitável',1,'S');

	INTO CAD_TP_ALERTA (TPA_DESCRICAO, TPA_GRAU, TPA_ATIVO)
		VALUES ('Em alerta',2,'S');

	INTO CAD_TP_ALERTA (TPA_DESCRICAO, TPA_GRAU, TPA_ATIVO)
		VALUES ('Em falha',3,'S');

SELECT * FROM DUAL;


--> FALTA


--> MAN_ROT_TEMP
INSERT ALL
	
	INSERT INTO MAN_ROT_TEMP (RTE_ID_POS, RTE_ID_COL, RTE_DATA, RTE_TEMP_AMB, RTE_TEMP_EQUIP, RTE_VELOCIDADE, RTE_OBS)
		VALUES ()
	
SELECT * FROM DUAL;



--> MAN_ROT_LUB
INSERT ALL

	INSERT INTO MAN_ROT_LUB (RLU_ID_POS, RLU_ID_COL, RLU_DATA, RLU_OBS)
		VALUES ()

SELECT * FROM DUAL;



--> MAN_OCORRENCIAS
INSERT ALL
	
	INSERT INTO MAN_OCORRENCIAS (OCO_ID_POS, OCO_DATA, OCO_OBS)
		VALUES ()

SELECT * FROM DUAL;



--> MAN_FALHA
INSERT ALL
	
	INSERT INTO MAN_FALHA (FAL_ID_POS, FAL_ID_R_TEMP, FAL_ID_R_LUB, FAL_ID_OCORRENCIA, FAL_ID_TP_ALERTA, FAL_DATA)
		VALUES ()
SELECT * FROM DUAL;





/* --> COMPLETAR DEPOIS --- 
UPDATE CAD_POSICAO
SET POS_TEMP_BASE = ?
WHERE POS_TAG = ?;

UPDATE CAD_POSICAO
SET POS_DT_PROX_LUB = ?
WHERE POS_TAG = ?;
*/